# Generated by Django 6.1 on 2026-09-11 12:56

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('employee_no', models.CharField(max_length=100, verbose_name='employee number')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name='father name')),
                ('staff_type', models.CharField(choices=[('teacher', 'Teacher'), ('administrative', 'Administrative'), ('support', 'Support')], default='teacher', max_length=20, verbose_name='staff type')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='national ID')),
                ('phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('qualification', models.CharField(blank=True, max_length=255, verbose_name='qualification')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='photo')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='joining date')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='leaving date')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='basic salary')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='login account')),
            ],
            options={
                'verbose_name': 'staff member',
                'verbose_name_plural': 'staff',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff', verbose_name='staff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='staff.staffdepartment', verbose_name='department')),
            ],
            options={
                'verbose_name': 'staff assignment',
                'verbose_name_plural': 'staff assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.staffdepartment', verbose_name='department'),
        ),
        migrations.CreateModel(
            name='StaffDesignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_teaching', models.BooleanField(default=False, verbose_name='teaching role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='staff.staffdepartment', verbose_name='department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'designation',
                'verbose_name_plural': 'designations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.staffdesignation', verbose_name='designation'),
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('degree', 'Degree'), ('id_card', 'ID Card'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=30, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('file', models.FileField(upload_to='staff/documents/', verbose_name='file')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='issued on')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='expires on')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name': 'staff document',
                'verbose_name_plural': 'staff documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('blood_group', models.CharField(blank=True, max_length=10, verbose_name='blood group')),
                ('marital_status', models.CharField(blank=True, max_length=30, verbose_name='marital status')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='emergency contact')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='emergency phone')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, max_length=60, verbose_name='bank account number')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='years of experience')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='staff.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name': 'staff profile',
                'verbose_name_plural': 'staff profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='previous status')),
                ('new_status', models.CharField(max_length=20, verbose_name='new status')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='staff.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name': 'staff status change',
                'verbose_name_plural': 'staff status history',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffdepartment',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_staff_department_name'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['staff', 'is_active'], name='staff_staff_staff_i_8d93a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffdesignation',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_staff_designation_name'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['organization', 'branch', 'status'], name='staff_staff_organiz_b707cc_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['branch', 'staff_type'], name='staff_staff_branch__b1c426_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['branch', 'full_name'], name='staff_staff_branch__9305ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('branch', 'employee_no'), name='uq_staff_employee_no'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='ck_staff_salary_positive'),
        ),
        migrations.AddIndex(
            model_name='staffdocument',
            index=models.Index(fields=['staff', 'document_type'], name='staff_staff_staff_i_6b685b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffstatushistory',
            index=models.Index(fields=['staff', 'effective_date'], name='staff_staff_staff_i_f9cec7_idx'),
        ),
    ]
