# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='staff.staff', verbose_name='class teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass', verbose_name='class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classsubject', verbose_name='class subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='staff.staff', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='term',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='term',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classsubject', verbose_name='class subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='staff.staff', verbose_name='teacher'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['branch', 'is_current'], name='academics_a_branch__b531ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_academic_year_name'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('branch',), name='uq_single_current_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='ck_academic_year_dates'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['branch', 'is_active'], name='academics_s_branch__c7e618_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uq_class_code'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_class_name'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['branch', 'school_class'], name='academics_s_branch__312a33_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school_class', 'name'), name='uq_section_name'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['branch', 'is_active'], name='academics_s_branch__bca516_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_subject_name'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['branch', 'academic_year', 'school_class'], name='academics_c_branch__fdbcd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('academic_year', 'school_class', 'subject'), name='uq_class_subject'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['branch', 'academic_year'], name='academics_t_branch__d1cdac_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'is_active'], name='academics_t_teacher_3f2cd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('class_subject', 'section', 'teacher'), name='uq_teacher_assignment'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['branch', 'is_current'], name='academics_t_branch__9d92c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='uq_term_name'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'sequence'), name='uq_term_sequence'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_term_dates'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['branch', 'academic_year', 'weekday'], name='academics_t_branch__c52b86_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher', 'weekday'], name='academics_t_teacher_9ef631_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('section', 'weekday', 'period', 'academic_year'), name='uq_timetable_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ck_timetable_times'),
        ),
    ]
