# Generated by Django 6.1 on 2026-09-11 12:56

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('grandparent', 'Grandparent'), ('other', 'Other')], default='father', max_length=30, verbose_name='relation')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='national ID')),
                ('phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='alternate phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='occupation')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='portal account')),
            ],
            options={
                'verbose_name': 'guardian',
                'verbose_name_plural': 'guardians',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('admission_no', models.CharField(max_length=100, verbose_name='admission number')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name='father name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=150, verbose_name='place of birth')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='nationality')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='national ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='photo')),
                ('phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('previous_institution', models.CharField(blank=True, max_length=255, verbose_name='previous institution')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='admission date')),
                ('is_boarder', models.BooleanField(default=False, verbose_name='boarder')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('expelled', 'Expelled')], default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='login account')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('moved_on', models.DateField(verbose_name='moved on')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_moves', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.schoolclass', verbose_name='class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.section', verbose_name='section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'class history entry',
                'verbose_name_plural': 'class history',
                'ordering': ['-moved_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('id_card', 'ID Card'), ('transfer_certificate', 'Transfer Certificate'), ('result_card', 'Result Card'), ('photo', 'Photograph'), ('other', 'Other')], default='other', max_length=40, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('file', models.FileField(upload_to='students/documents/', verbose_name='file')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='issued on')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student document',
                'verbose_name_plural': 'student documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('roll_number', models.CharField(blank=True, max_length=50, verbose_name='roll number')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_current', models.BooleanField(default=True, verbose_name='current')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.schoolclass', verbose_name='class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.section', verbose_name='section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('relation', models.CharField(blank=True, max_length=50, verbose_name='relation')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary contact')),
                ('can_view_portal', models.BooleanField(default=True, verbose_name='portal access')),
                ('can_collect_student', models.BooleanField(default=True, verbose_name='authorised for pickup')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.guardian', verbose_name='guardian')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student guardian',
                'verbose_name_plural': 'student guardians',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('blood_group', models.CharField(blank=True, max_length=10, verbose_name='blood group')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='medical conditions')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='emergency contact')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='emergency phone')),
                ('transport_required', models.BooleanField(default=False, verbose_name='transport required')),
                ('hostel_room', models.CharField(blank=True, max_length=50, verbose_name='hostel room')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='previous status')),
                ('new_status', models.CharField(max_length=20, verbose_name='new status')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'status change',
                'verbose_name_plural': 'status history',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['branch', 'full_name'], name='students_gu_branch__6e844e_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['branch', 'phone'], name='students_gu_branch__73f2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'branch', 'status'], name='students_st_organiz_250e90_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'full_name'], name='students_st_branch__a2866e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'admission_no'], name='students_st_branch__1fc6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'created_at'], name='students_st_branch__9f1e75_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('branch', 'admission_no'), name='uq_student_admission_no'),
        ),
        migrations.AddIndex(
            model_name='studentclasshistory',
            index=models.Index(fields=['student', 'moved_on'], name='students_st_student_e0d7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', 'document_type'], name='students_st_student_7712b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['branch', 'academic_year', 'school_class', 'section'], name='students_st_branch__97142f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'is_current'], name='students_st_student_a25061_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['branch', 'is_current'], name='students_st_branch__4af57e_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='uq_student_year_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='uq_student_single_current_enrollment'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['guardian', 'can_view_portal'], name='students_st_guardia_f72ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['student', 'is_primary'], name='students_st_student_428fb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='uq_student_guardian'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='uq_student_primary_guardian'),
        ),
        migrations.AddIndex(
            model_name='studentstatushistory',
            index=models.Index(fields=['student', 'effective_date'], name='students_st_student_faa546_idx'),
        ),
    ]
