# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(max_length=150, verbose_name='key')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='value')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_editable', models.BooleanField(default=True, verbose_name='editable')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'system setting',
                'verbose_name_plural': 'system settings',
                'ordering': ['key'],
                'permissions': [('access_dashboard', 'Can access the dashboard'), ('access_academics', 'Can access academics'), ('access_students', 'Can access students'), ('access_staff', 'Can access staff'), ('access_attendance', 'Can access attendance'), ('access_hifz', 'Can access hifz'), ('access_fees', 'Can access fees'), ('access_finance', 'Can access finance'), ('access_payroll', 'Can access payroll'), ('access_exams', 'Can access exams'), ('access_parents', 'Can access the parent portal'), ('access_notifications', 'Can access notifications'), ('access_reports', 'Can access reports'), ('access_subscriptions', 'Can access subscriptions'), ('access_audit', 'Can access audit logs'), ('access_settings', 'Can access administrative settings'), ('collect_fee_payment', 'Can collect fee payments'), ('refund_fee_payment', 'Can refund fee payments'), ('waive_fee', 'Can waive or discount fees'), ('post_journal_entry', 'Can post finance journal entries'), ('run_payroll', 'Can run payroll'), ('publish_exam_result', 'Can publish exam results'), ('restore_record', 'Can restore deleted records'), ('export_report', 'Can export reports'), ('import_data', 'Can import data'), ('manage_roles', 'Can manage roles and permissions'), ('manage_branches', 'Can manage branches'), ('switch_branch', 'Can switch between branches'), ('view_all_branches', 'Can view data across all accessible branches')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='uq_system_setting_key')],
            },
        ),
    ]
