# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPortalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receives_attendance_alerts', models.BooleanField(default=True, verbose_name='attendance alerts')),
                ('receives_fee_reminders', models.BooleanField(default=True, verbose_name='fee reminders')),
                ('receives_result_alerts', models.BooleanField(default=True, verbose_name='result alerts')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('default_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_guardians', to='students.student', verbose_name='default child')),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to='students.guardian', verbose_name='guardian')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'parent portal profile',
                'verbose_name_plural': 'parent portal profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('request_type', models.CharField(choices=[('leave', 'Leave Request'), ('query', 'General Query'), ('document', 'Document Request'), ('meeting', 'Meeting Request'), ('complaint', 'Complaint')], default='query', max_length=20, verbose_name='type')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='from')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='to')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='status')),
                ('response', models.TextField(blank=True, verbose_name='response')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='students.guardian', verbose_name='guardian')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_request_responses', to=settings.AUTH_USER_MODEL, verbose_name='responded by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_requests', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'parent request',
                'verbose_name_plural': 'parent requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status', 'created_at'], name='parents_par_branch__b7cbd8_idx'), models.Index(fields=['guardian', 'status'], name='parents_par_guardia_85fabf_idx'), models.Index(fields=['student', 'status'], name='parents_par_student_4d4426_idx')],
            },
        ),
    ]
