# Generated by Django 6.1 on 2026-09-11 12:56

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='legal name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('country', models.CharField(default='Pakistan', max_length=120, verbose_name='country')),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=100, verbose_name='timezone')),
                ('currency', models.CharField(default='PKR', max_length=10, verbose_name='currency')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic')], default='en', max_length=5, verbose_name='default language')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='trial', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='tenants_org_status_134ebb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='code')),
                ('phone', models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_central_administration', models.BooleanField(default=False, verbose_name='central administration')),
                ('opened_on', models.DateField(blank=True, null=True, verbose_name='opened on')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['organization__name', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='tenants_bra_organiz_0fd6ac_idx'), models.Index(fields=['organization', 'is_central_administration'], name='tenants_bra_organiz_ff4ad2_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uq_branch_code'), models.UniqueConstraint(fields=('organization', 'name'), name='uq_branch_name')],
            },
        ),
    ]
