# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='monthly price')),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='yearly price')),
                ('currency', models.CharField(default='PKR', max_length=10, verbose_name='currency')),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True, verbose_name='branch limit')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name='student limit')),
                ('max_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='user limit')),
                ('storage_limit_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='storage limit (MB)')),
                ('monthly_sms_limit', models.PositiveIntegerField(default=0, verbose_name='SMS per month')),
                ('monthly_whatsapp_limit', models.PositiveIntegerField(default=0, verbose_name='WhatsApp per month')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='features')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='billing cycle')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('trial_ends_on', models.DateField(blank=True, null=True, verbose_name='trial ends')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20, verbose_name='status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='auto renew')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metric', models.CharField(max_length=60, verbose_name='metric')),
                ('period_month', models.DateField(verbose_name='month')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='used')),
                ('limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='limit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='subscriptions.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'feature usage',
                'verbose_name_plural': 'feature usage',
                'ordering': ['-period_month', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='invoice number')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='tax')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='paid on')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=20, verbose_name='status')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'subscription invoice',
                'verbose_name_plural': 'subscription invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='subscriptio_organiz_3cb096_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trial', 'active', 'past_due'])), fields=('organization',), name='uq_organization_live_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_subscription_dates'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['organization', 'metric', 'period_month'], name='subscriptio_organiz_c86e7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='featureusage',
            constraint=models.UniqueConstraint(fields=('subscription', 'metric', 'period_month'), name='uq_feature_usage'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='uq_subscription_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ck_subscription_invoice_total'),
        ),
    ]
