# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='invoice number')),
                ('period_month', models.DateField(blank=True, help_text='First day of the month this invoice covers.', null=True, verbose_name='billing month')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount')),
                ('waiver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='waiver')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='paid')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='refunded')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student', verbose_name='student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='academics.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'fee invoice',
                'verbose_name_plural': 'fee invoices',
                'ordering': ['-issue_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='receipt number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('payment_date', models.DateField(db_index=True, verbose_name='payment date')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='reference')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('is_void', models.BooleanField(default=False, verbose_name='void')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('void_reason', models.CharField(blank=True, max_length=255, verbose_name='void reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feeinvoice', verbose_name='invoice')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payment', to='finance.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='finance.paymentmethod', verbose_name='payment method')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='received by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'fee payment',
                'verbose_name_plural': 'fee payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('refund_number', models.CharField(max_length=50, verbose_name='refund number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('refund_date', models.DateField(verbose_name='refund date')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_refund', to='finance.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='fees.feepayment', verbose_name='payment')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_refunds', to='finance.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'fee refund',
                'verbose_name_plural': 'fee refunds',
                'ordering': ['-refund_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='code')),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('term', 'Per Term'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='frequency')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_refundable', models.BooleanField(default=False, verbose_name='refundable')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_types', to='finance.account', verbose_name='income account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'fee type',
                'verbose_name_plural': 'fee types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='mandatory')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.schoolclass', verbose_name='class')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='fees.feetype', verbose_name='fee type')),
            ],
            options={
                'verbose_name': 'fee structure',
                'verbose_name_plural': 'fee structures',
                'ordering': ['school_class__level', 'fee_type__name'],
            },
        ),
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='unit amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='line total')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice', verbose_name='invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='fees.feetype', verbose_name='fee type')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='discount type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='value')),
                ('valid_from', models.DateField(verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valid to')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student', verbose_name='student')),
                ('fee_type', models.ForeignKey(blank=True, help_text='Leave empty to apply to every fee type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='fees.feetype', verbose_name='fee type')),
            ],
            options={
                'verbose_name': 'fee discount',
                'verbose_name_plural': 'fee discounts',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('waived_on', models.DateField(verbose_name='waived on')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_waivers', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waivers', to='fees.feeinvoice', verbose_name='invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'fee waiver',
                'verbose_name_plural': 'fee waivers',
                'ordering': ['-waived_on'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fees.feetype', verbose_name='fee type')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student fee',
                'verbose_name_plural': 'student fees',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['branch', 'status', 'due_date'], name='fees_feeinv_branch__e5d3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student', 'status'], name='fees_feeinv_student_c0e8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['branch', 'issue_date'], name='fees_feeinv_branch__579b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['branch', 'academic_year', 'period_month'], name='fees_feeinv_branch__e0bc43_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(fields=('branch', 'invoice_number'), name='uq_fee_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('period_month__isnull', False)), fields=('student', 'academic_year', 'period_month'), name='uq_student_monthly_invoice'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0), ('paid_amount__gte', 0)), name='ck_fee_invoice_amounts'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['branch', 'payment_date'], name='fees_feepay_branch__1641dd_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student', 'payment_date'], name='fees_feepay_student_198476_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['invoice', 'is_void'], name='fees_feepay_invoice_4e0ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['branch', 'is_void', 'payment_date'], name='fees_feepay_branch__8f9caa_idx'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('branch', 'receipt_number'), name='uq_fee_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_fee_payment_amount'),
        ),
        migrations.AddIndex(
            model_name='feerefund',
            index=models.Index(fields=['branch', 'refund_date'], name='fees_feeref_branch__e10c6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='feerefund',
            constraint=models.UniqueConstraint(fields=('branch', 'refund_number'), name='uq_fee_refund_number'),
        ),
        migrations.AddConstraint(
            model_name='feerefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_fee_refund_amount'),
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['branch', 'is_active'], name='fees_feetyp_branch__7b0dcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_fee_type_name'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['branch', 'academic_year', 'school_class'], name='fees_feestr_branch__c64e4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('academic_year', 'school_class', 'fee_type'), name='uq_fee_structure'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_fee_structure_amount'),
        ),
        migrations.AddIndex(
            model_name='feeinvoiceitem',
            index=models.Index(fields=['invoice', 'fee_type'], name='fees_feeinv_invoice_5a8575_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0), ('discount_amount__gte', 0)), name='ck_invoice_item_amounts'),
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['branch', 'student', 'is_active'], name='fees_feedis_branch__d84e33_idx'),
        ),
        migrations.AddConstraint(
            model_name='feediscount',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='ck_fee_discount_value'),
        ),
        migrations.AddIndex(
            model_name='feewaiver',
            index=models.Index(fields=['branch', 'waived_on'], name='fees_feewai_branch__0cff6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='feewaiver',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_fee_waiver_amount'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['branch', 'student', 'is_active'], name='fees_studen_branch__41dfb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'fee_type', 'effective_from'), name='uq_student_fee'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_student_fee_amount'),
        ),
    ]
