# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('session_type', models.CharField(choices=[('daily', 'Daily'), ('period', 'Period'), ('exam', 'Exam'), ('event', 'Event')], default='daily', max_length=20, verbose_name='session type')),
                ('period', models.PositiveSmallIntegerField(default=0, verbose_name='period')),
                ('is_locked', models.BooleanField(default=False, verbose_name='locked')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.schoolclass', verbose_name='class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.section', verbose_name='section')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='taken by')),
            ],
            options={
                'verbose_name': 'attendance session',
                'verbose_name_plural': 'attendance sessions',
                'ordering': ['-date', 'school_class__level'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused')], default='present', max_length=20, verbose_name='status')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='check in')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='check out')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='staff.staff', verbose_name='staff')),
            ],
            options={
                'verbose_name': 'staff attendance',
                'verbose_name_plural': 'staff attendance',
                'ordering': ['-date', 'staff__full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave'), ('excused', 'Excused')], default='present', max_length=20, verbose_name='status')),
                ('minutes_late', models.PositiveSmallIntegerField(default=0, verbose_name='minutes late')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession', verbose_name='session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student attendance',
                'verbose_name_plural': 'student attendance',
                'ordering': ['-date', 'student__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['branch', 'date'], name='attendance__branch__24f566_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['branch', 'academic_year', 'date'], name='attendance__branch__8e619c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['school_class', 'date'], name='attendance__school__eff945_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('branch', 'school_class', 'section', 'date', 'period'), name='uq_attendance_session'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['branch', 'date', 'status'], name='attendance__branch__fe3fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='attendance__staff_i_d77b2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='uq_staff_daily_attendance'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_0335ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['branch', 'date', 'status'], name='attendance__branch__b09703_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['branch', 'status'], name='attendance__branch__db110b_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uq_attendance_session_student'),
        ),
    ]
