# Generated by Django 6.1 on 2026-09-11 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='uq_attendance_session',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_subject',
            field=models.ForeignKey(blank=True, help_text='Set for subject or period attendance; empty for the daily register.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.classsubject', verbose_name='subject'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_subject', 'date'], name='attendance__class_s_447209_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('class_subject__isnull', True)), fields=('branch', 'school_class', 'section', 'date', 'period'), name='uq_attendance_session_daily'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('class_subject__isnull', False)), fields=('branch', 'school_class', 'section', 'date', 'period', 'class_subject'), name='uq_attendance_session_subject'),
        ),
    ]
