# Generated by Django 6.1 on 2026-09-11 12:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HifzStudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stage', models.CharField(choices=[('qaida', 'Qaida'), ('nazra', 'Nazra'), ('hifz', 'Hifz'), ('revision', 'Full Revision'), ('completed', 'Completed')], default='qaida', max_length=20, verbose_name='stage')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='started on')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='completed on')),
                ('current_para', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='current para')),
                ('current_surah', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(114)], verbose_name='current surah')),
                ('paras_memorized', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='paras memorized')),
                ('daily_target_lines', models.PositiveSmallIntegerField(default=0, verbose_name='daily target (lines)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_profile', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'hifz student',
                'verbose_name_plural': 'hifz students',
                'ordering': ['student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='HifzAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('from_para', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='from para')),
                ('to_para', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='to para')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='total marks')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='obtained marks')),
                ('mistakes', models.PositiveSmallIntegerField(default=0, verbose_name='mistakes')),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('repeat', 'Repeat')], default='passed', max_length=20, verbose_name='result')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hifz_assessments', to='staff.staff', verbose_name='examiner')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('hifz_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hifz.hifzstudentprofile', verbose_name='hifz student')),
            ],
            options={
                'verbose_name': 'hifz assessment',
                'verbose_name_plural': 'hifz assessments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('lesson_type', models.CharField(choices=[('sabaq', 'Sabaq (new lesson)'), ('sabqi', 'Sabqi (recent revision)'), ('manzil', 'Manzil (old revision)'), ('nazra', 'Nazra (recitation)'), ('qaida', 'Qaida (foundation)')], max_length=20, verbose_name='lesson type')),
                ('from_para', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='from para')),
                ('to_para', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='to para')),
                ('surah', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(114)], verbose_name='surah')),
                ('from_ayah', models.PositiveIntegerField(blank=True, null=True, verbose_name='from ayah')),
                ('to_ayah', models.PositiveIntegerField(blank=True, null=True, verbose_name='to ayah')),
                ('lines', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='lines')),
                ('pages', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='pages')),
                ('mistakes', models.PositiveSmallIntegerField(default=0, verbose_name='mistakes')),
                ('hesitations', models.PositiveSmallIntegerField(default=0, verbose_name='hesitations')),
                ('quality', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Weak')], null=True, verbose_name='quality')),
                ('is_repeated', models.BooleanField(default=False, verbose_name='repeated')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heard_progress', to='staff.staff', verbose_name='heard by')),
                ('hifz_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='hifz.hifzstudentprofile', verbose_name='hifz student')),
            ],
            options={
                'verbose_name': 'daily progress',
                'verbose_name_plural': 'daily progress',
                'ordering': ['-date', 'lesson_type'],
            },
        ),
        migrations.CreateModel(
            name='HifzTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('hifz_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='hifz.hifzstudentprofile', verbose_name='hifz student')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_assignments', to='staff.staff', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'hifz teacher assignment',
                'verbose_name_plural': 'hifz teacher assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('from_para', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='from para')),
                ('to_para', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='to para')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='completed date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='planned', max_length=20, verbose_name='status')),
                ('mistakes', models.PositiveSmallIntegerField(default=0, verbose_name='mistakes')),
                ('quality', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Weak')], null=True, verbose_name='quality')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('hifz_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='hifz.hifzstudentprofile', verbose_name='hifz student')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hifz_revisions', to='staff.staff', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'revision',
                'verbose_name_plural': 'revisions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='hifzstudentprofile',
            index=models.Index(fields=['branch', 'stage', 'is_active'], name='hifz_hifzst_branch__c16d50_idx'),
        ),
        migrations.AddIndex(
            model_name='hifzstudentprofile',
            index=models.Index(fields=['branch', 'current_para'], name='hifz_hifzst_branch__99d482_idx'),
        ),
        migrations.AddConstraint(
            model_name='hifzstudentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('paras_memorized__gte', 0), ('paras_memorized__lte', 30)), name='ck_hifz_paras_range'),
        ),
        migrations.AddIndex(
            model_name='hifzassessment',
            index=models.Index(fields=['branch', 'date'], name='hifz_hifzas_branch__16eeff_idx'),
        ),
        migrations.AddIndex(
            model_name='hifzassessment',
            index=models.Index(fields=['hifz_profile', 'date'], name='hifz_hifzas_hifz_pr_0f7146_idx'),
        ),
        migrations.AddConstraint(
            model_name='hifzassessment',
            constraint=models.CheckConstraint(condition=models.Q(('obtained_marks__gte', 0), ('obtained_marks__lte', models.F('total_marks'))), name='ck_hifz_assessment_marks'),
        ),
        migrations.AddConstraint(
            model_name='hifzassessment',
            constraint=models.CheckConstraint(condition=models.Q(('to_para__gte', models.F('from_para'))), name='ck_hifz_assessment_range'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['branch', 'date', 'lesson_type'], name='hifz_dailyp_branch__18e28d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['hifz_profile', 'date'], name='hifz_dailyp_hifz_pr_f4159c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['teacher', 'date'], name='hifz_dailyp_teacher_35c58e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(fields=('hifz_profile', 'date', 'lesson_type'), name='uq_hifz_daily_lesson'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('mistakes__gte', 0)), name='ck_hifz_mistakes'),
        ),
        migrations.AddIndex(
            model_name='hifzteacherassignment',
            index=models.Index(fields=['teacher', 'is_active'], name='hifz_hifzte_teacher_1cac7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='hifzteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('hifz_profile',), name='uq_active_hifz_teacher'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['branch', 'scheduled_date', 'status'], name='hifz_revisi_branch__2b905a_idx'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['hifz_profile', 'status'], name='hifz_revisi_hifz_pr_bf2132_idx'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('to_para__gte', models.F('from_para'))), name='ck_revision_para_range'),
        ),
    ]
