# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('username', models.CharField(blank=True, help_text='Kept verbatim so the trail survives a deleted account.', max_length=150, verbose_name='username')),
                ('role_name', models.CharField(blank=True, max_length=150, verbose_name='role')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('export', 'Export'), ('import', 'Import'), ('permission_change', 'Permission Change'), ('role_change', 'Role Change'), ('branch_change', 'Branch Change'), ('settings_change', 'Settings Change'), ('payment', 'Payment'), ('refund', 'Refund'), ('payroll', 'Payroll'), ('publish', 'Publish'), ('access_denied', 'Access Denied'), ('other', 'Other')], max_length=40, verbose_name='action')),
                ('app_label', models.CharField(blank=True, max_length=100, verbose_name='module')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='resource')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='object id')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='object')),
                ('previous_values', models.JSONField(blank=True, null=True, verbose_name='previous values')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='new values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='method')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tenants.organization', verbose_name='organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity log',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_activ_organiz_cc28b3_idx'), models.Index(fields=['branch', '-created_at'], name='audit_activ_branch__b57ff3_idx'), models.Index(fields=['user', '-created_at'], name='audit_activ_user_id_60d287_idx'), models.Index(fields=['action', '-created_at'], name='audit_activ_action_f38451_idx'), models.Index(fields=['app_label', 'model_name'], name='audit_activ_app_lab_7cde07_idx'), models.Index(fields=['object_id'], name='audit_activ_object__d4ac8c_idx')],
            },
        ),
    ]
