# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('marking', 'Marking'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exams', to=settings.AUTH_USER_MODEL, verbose_name='published by')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.schoolclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=7, verbose_name='total marks')),
                ('passing_marks', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=7, verbose_name='passing marks')),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='weight %')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='academics.classsubject', verbose_name='subject')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exams.exam', verbose_name='exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'exam subject',
                'verbose_name_plural': 'exam subjects',
                'ordering': ['class_subject__subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='room')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilations', to='staff.staff', verbose_name='invigilator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.section', verbose_name='section')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.examsubject', verbose_name='exam subject')),
            ],
            options={
                'verbose_name': 'exam schedule',
                'verbose_name_plural': 'exam schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='sequence')),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='weight %')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_terms', to='academics.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'exam term',
                'verbose_name_plural': 'exam terms',
                'ordering': ['academic_year', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.examterm', verbose_name='exam term'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=20, verbose_name='grade')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='minimum %')),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='maximum %')),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='grade point')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='remark')),
                ('is_pass', models.BooleanField(default=True, verbose_name='counts as pass')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.academicyear', verbose_name='academic year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grading scale',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('roll_number', models.CharField(blank=True, max_length=50, verbose_name='roll number')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('appeared', 'Appeared'), ('absent', 'Absent'), ('exempted', 'Exempted'), ('disqualified', 'Disqualified')], default='registered', max_length=20, verbose_name='status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='exams.exam', verbose_name='exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exams', to='academics.section', verbose_name='section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_exams', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student exam',
                'verbose_name_plural': 'student exams',
                'ordering': ['student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='total marks')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='obtained marks')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='percentage')),
                ('subjects_passed', models.PositiveSmallIntegerField(default=0, verbose_name='subjects passed')),
                ('subjects_failed', models.PositiveSmallIntegerField(default=0, verbose_name='subjects failed')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='position')),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='outcome')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='generated at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='exams.grade', verbose_name='grade')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='exams.studentexam', verbose_name='student exam')),
            ],
            options={
                'verbose_name': 'result summary',
                'verbose_name_plural': 'result summaries',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='obtained marks')),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='total marks')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='percentage')),
                ('is_pass', models.BooleanField(default=False, verbose_name='passed')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examsubject', verbose_name='exam subject')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='exams.grade', verbose_name='grade')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.studentexam', verbose_name='student exam')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
                'ordering': ['exam_subject__class_subject__subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='obtained marks')),
                ('is_absent', models.BooleanField(default=False, verbose_name='absent')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='remarks')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL, verbose_name='entered by')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.examsubject', verbose_name='exam subject')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.studentexam', verbose_name='student exam')),
            ],
            options={
                'verbose_name': 'mark',
                'verbose_name_plural': 'marks',
                'ordering': ['exam_subject__class_subject__subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='examsubject',
            index=models.Index(fields=['branch', 'exam'], name='exams_exams_branch__6c7d25_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'class_subject'), name='uq_exam_subject'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.CheckConstraint(condition=models.Q(('passing_marks__lte', models.F('total_marks'))), name='ck_exam_subject_marks'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['branch', 'date'], name='exams_exams_branch__f200bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('exam_subject', 'section'), name='uq_exam_schedule'),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ck_exam_schedule_times'),
        ),
        migrations.AddConstraint(
            model_name='examterm',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='uq_exam_term_name'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['branch', 'academic_year', 'status'], name='exams_exam_branch__ea2467_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['branch', 'start_date'], name='exams_exam_branch__bf1855_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('branch', 'exam_term', 'school_class', 'name'), name='uq_exam_name'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['branch', 'academic_year'], name='exams_grade_branch__2c3c45_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='uq_grade_name'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('max_percentage__gte', models.F('min_percentage'))), name='ck_grade_range'),
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['branch', 'exam', 'status'], name='exams_stude_branch__c059c0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexam',
            index=models.Index(fields=['student', 'exam'], name='exams_stude_student_2fba81_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexam',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='uq_student_exam'),
        ),
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['branch', 'outcome'], name='exams_resul_branch__214909_idx'),
        ),
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['branch', 'percentage'], name='exams_resul_branch__d03a93_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['branch', 'student_exam'], name='exams_resul_branch__abb829_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['branch', 'exam_subject', 'is_pass'], name='exams_resul_branch__7cd4d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('student_exam', 'exam_subject'), name='uq_subject_result'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['branch', 'exam_subject'], name='exams_mark_branch__0bf7f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('student_exam', 'exam_subject'), name='uq_student_subject_mark'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(('obtained_marks__gte', 0)), name='ck_mark_non_negative'),
        ),
    ]
