"""Default permission sets for the seeded roles.

These are starting points written to the database, not authorization logic.
An administrator can edit any of them afterwards, and new roles need no entry
here at all.
"""

from apps.core.constants import (
    ROLE_ADMIN,
    ROLE_FEES_COLLECTOR,
    ROLE_FINANCE,
    ROLE_PARENT,
    ROLE_STUDENT,
    ROLE_TEACHER,
)

#: ``"*"`` means every permission that exists.
ROLE_PRESETS = {
    ROLE_ADMIN: {"description": "Full access within the organization", "permissions": "*"},
    ROLE_TEACHER: {
        "description": "Teaching staff: classes, attendance, hifz and marks",
        "permissions": [
            "core.access_dashboard",
            "core.access_academics",
            "core.access_students",
            "core.access_attendance",
            "core.access_hifz",
            "core.access_exams",
            "core.access_reports",
            "core.access_notifications",
            "academics.view_academicyear",
            "academics.view_term",
            "academics.view_schoolclass",
            "academics.view_section",
            "academics.view_subject",
            "academics.view_classsubject",
            "academics.view_teacherassignment",
            "academics.view_timetable",
            "students.view_student",
            "students.view_studentenrollment",
            "attendance.view_attendancesession",
            "attendance.add_attendancesession",
            "attendance.change_attendancesession",
            "attendance.view_studentattendance",
            "attendance.add_studentattendance",
            "attendance.change_studentattendance",
            "hifz.view_hifzstudentprofile",
            "hifz.view_dailyprogress",
            "hifz.add_dailyprogress",
            "hifz.change_dailyprogress",
            "hifz.view_hifzassessment",
            "hifz.add_hifzassessment",
            "exams.view_exam",
            "exams.view_examsubject",
            "exams.view_examschedule",
            "exams.view_mark",
            "exams.add_mark",
            "exams.change_mark",
            "exams.view_result",
            "notifications.view_notification",
        ],
    },
    ROLE_FEES_COLLECTOR: {
        "description": "Front desk: invoicing and fee collection",
        "permissions": [
            "core.access_dashboard",
            "core.access_students",
            "core.access_fees",
            "core.access_reports",
            "core.access_notifications",
            "core.collect_fee_payment",
            "core.export_report",
            "students.view_student",
            "students.view_studentenrollment",
            "fees.view_feetype",
            "fees.view_feestructure",
            "fees.view_studentfee",
            "fees.view_feeinvoice",
            "fees.add_feeinvoice",
            "fees.change_feeinvoice",
            "fees.view_feeinvoiceitem",
            "fees.view_feepayment",
            "fees.add_feepayment",
            "fees.view_feediscount",
            "notifications.view_notification",
        ],
    },
    ROLE_FINANCE: {
        "description": "Accounts office: ledgers, payroll and refunds",
        "permissions": [
            "core.access_dashboard",
            "core.access_fees",
            "core.access_finance",
            "core.access_payroll",
            "core.access_reports",
            "core.access_notifications",
            "core.collect_fee_payment",
            "core.refund_fee_payment",
            "core.waive_fee",
            "core.post_journal_entry",
            "core.run_payroll",
            "core.export_report",
            "fees.view_feetype",
            "fees.add_feetype",
            "fees.change_feetype",
            "fees.view_feestructure",
            "fees.add_feestructure",
            "fees.change_feestructure",
            "fees.view_feeinvoice",
            "fees.add_feeinvoice",
            "fees.change_feeinvoice",
            "fees.view_feepayment",
            "fees.add_feepayment",
            "fees.view_feerefund",
            "fees.add_feerefund",
            "fees.view_feediscount",
            "fees.add_feediscount",
            "fees.view_feewaiver",
            "fees.add_feewaiver",
            "finance.view_account",
            "finance.add_account",
            "finance.change_account",
            "finance.view_accounttype",
            "finance.view_journal",
            "finance.add_journal",
            "finance.view_journalentry",
            "finance.add_journalentry",
            "finance.view_transaction",
            "finance.view_fiscalperiod",
            "finance.add_fiscalperiod",
            "finance.change_fiscalperiod",
            "finance.view_paymentmethod",
            "payroll.view_salarycomponent",
            "payroll.add_salarycomponent",
            "payroll.view_salarystructure",
            "payroll.add_salarystructure",
            "payroll.change_salarystructure",
            "payroll.view_employeesalary",
            "payroll.add_employeesalary",
            "payroll.view_payrollperiod",
            "payroll.add_payrollperiod",
            "payroll.view_payrollrun",
            "payroll.add_payrollrun",
            "payroll.view_payrollitem",
            "payroll.view_salarypayment",
            "payroll.add_salarypayment",
            "notifications.view_notification",
        ],
    },
    ROLE_STUDENT: {
        "description": "Student self-service",
        "permissions": [
            "core.access_dashboard",
            "core.access_notifications",
            "notifications.view_notification",
        ],
    },
    ROLE_PARENT: {
        "description": "Parent portal: own children only",
        "permissions": [
            "core.access_parents",
            "core.access_notifications",
            "notifications.view_notification",
        ],
    },
}
