# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('report_key', models.CharField(max_length=150, verbose_name='report')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='rows')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to='tenants.branch', verbose_name='branch')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to=settings.AUTH_USER_MODEL, verbose_name='exported by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'report export',
                'verbose_name_plural': 'report exports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'report_key', 'created_at'], name='reports_rep_organiz_9011a3_idx'), models.Index(fields=['exported_by', 'created_at'], name='reports_rep_exporte_0d7faf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('report_key', models.CharField(max_length=150, verbose_name='report')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('is_shared', models.BooleanField(default=False, verbose_name='shared with colleagues')),
                ('branch', models.ForeignKey(blank=True, help_text='Leave empty for an organization-wide report.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='tenants.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'saved report',
                'verbose_name_plural': 'saved reports',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'report_key'], name='reports_sav_organiz_858a99_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'created_by', 'name'), name='uq_saved_report_name')],
            },
        ),
    ]
