# Generated by Django 6.1 on 2026-09-11 12:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('month', models.DateField(help_text='First day of the month.', verbose_name='month')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'payroll period',
                'verbose_name_plural': 'payroll periods',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference', models.CharField(max_length=50, verbose_name='reference')),
                ('run_date', models.DateField(verbose_name='run date')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total gross')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total deductions')),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total net')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='employees')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_run', to='finance.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollperiod', verbose_name='period')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
            ],
            options={
                'verbose_name': 'payroll run',
                'verbose_name_plural': 'payroll runs',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='basic salary')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='allowances')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='deductions')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='gross salary')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='net salary')),
                ('days_present', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='days present')),
                ('days_absent', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='days absent')),
                ('breakdown', models.JSONField(blank=True, default=list, verbose_name='breakdown')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='staff.staff', verbose_name='staff')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrun', verbose_name='run')),
            ],
            options={
                'verbose_name': 'payroll item',
                'verbose_name_plural': 'payroll items',
                'ordering': ['staff__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(max_length=40, verbose_name='code')),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20, verbose_name='type')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_basic', 'Percentage of Basic')], default='fixed', max_length=20, verbose_name='calculation')),
                ('default_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='default value')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='taxable')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_components', to='finance.account', verbose_name='expense account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'salary component',
                'verbose_name_plural': 'salary components',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='voucher number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='reference')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payment', to='finance.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='paid by')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='finance.paymentmethod', verbose_name='payment method')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll.payrollitem', verbose_name='payroll item')),
            ],
            options={
                'verbose_name': 'salary payment',
                'verbose_name_plural': 'salary payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='basic salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'salary structure',
                'verbose_name_plural': 'salary structures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='basic salary')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('bank_account_number', models.CharField(blank=True, max_length=60, verbose_name='bank account')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='staff.staff', verbose_name='staff')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salaries', to='payroll.salarystructure', verbose_name='structure')),
            ],
            options={
                'verbose_name': 'employee salary',
                'verbose_name_plural': 'employee salaries',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='value')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='sequence')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.branch', verbose_name='branch')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_lines', to='payroll.salarycomponent', verbose_name='component')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='organization')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salarystructure', verbose_name='structure')),
            ],
            options={
                'verbose_name': 'structure line',
                'verbose_name_plural': 'structure lines',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['branch', 'status', 'month'], name='payroll_pay_branch__6da4ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('branch', 'month'), name='uq_payroll_period_month'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_payroll_period_dates'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['branch', 'status', 'run_date'], name='payroll_pay_branch__4a9068_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('branch', 'reference'), name='uq_payroll_run_reference'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('total_net__gte', 0)), name='ck_payroll_run_net'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['branch', 'run', 'staff'], name='payroll_pay_branch__d0c882_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.UniqueConstraint(fields=('run', 'staff'), name='uq_payroll_run_staff'),
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.CheckConstraint(condition=models.Q(('net_salary__gte', 0)), name='ck_payroll_item_net'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uq_salary_component_code'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('default_value__gte', 0)), name='ck_salary_component_value'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['branch', 'payment_date'], name='payroll_sal_branch__93471f_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(fields=('branch', 'voucher_number'), name='uq_salary_voucher_number'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_salary_payment_amount'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uq_salary_structure_name'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='ck_salary_structure_basic'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['branch', 'staff', 'is_active'], name='payroll_emp_branch__a00f2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeesalary',
            constraint=models.UniqueConstraint(fields=('staff', 'effective_from'), name='uq_employee_salary_from'),
        ),
        migrations.AddConstraint(
            model_name='employeesalary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('staff',), name='uq_employee_single_active_salary'),
        ),
        migrations.AddConstraint(
            model_name='employeesalary',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='ck_employee_salary_basic'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.UniqueConstraint(fields=('structure', 'component'), name='uq_structure_component'),
        ),
    ]
